package model;
// Generated Dec 6, 2019 10:16:38 PM by Hibernate Tools 4.3.1



/**
 * KorisnikProjekatId generated by hbm2java
 */
public class KorisnikProjekatId  implements java.io.Serializable {


     private int idkorisnik;
     private int idprojekat;

    public KorisnikProjekatId() {
    }

    public KorisnikProjekatId(int idkorisnik, int idprojekat) {
       this.idkorisnik = idkorisnik;
       this.idprojekat = idprojekat;
    }
   
    public int getIdkorisnik() {
        return this.idkorisnik;
    }
    
    public void setIdkorisnik(int idkorisnik) {
        this.idkorisnik = idkorisnik;
    }
    public int getIdprojekat() {
        return this.idprojekat;
    }
    
    public void setIdprojekat(int idprojekat) {
        this.idprojekat = idprojekat;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KorisnikProjekatId) ) return false;
		 KorisnikProjekatId castOther = ( KorisnikProjekatId ) other; 
         
		 return (this.getIdkorisnik()==castOther.getIdkorisnik())
 && (this.getIdprojekat()==castOther.getIdprojekat());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdkorisnik();
         result = 37 * result + this.getIdprojekat();
         return result;
   }   


}


