package model;
// Generated Dec 6, 2019 10:16:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik implements java.io.Serializable {

    private Integer idkorisnik;
    private String ime;
    private String prezime;
    private String korisnickoIme;
    private String lozinka;
    private String nacionalnost;
    private String zemljaZaposlenja;
    private String nioZaposlenja;
    private String naucnoZvanje;
    private String angazovanje;
    private String strucneOblasti;
    private String mobilni;
    private String email;
    private String adresa;
    private String vebStranica;
    private String nazivBiografije;
    private Long privremenaLozinkaPostavljena;
    private String stanje;
    private Set korisnikProjekats = new HashSet(0);

    public Korisnik() {
    }

    public Korisnik(String ime, String prezime, String korisnickoIme, String lozinka, String email, String nazivBiografije, String stanje) {
        this.ime = ime;
        this.prezime = prezime;
        this.korisnickoIme = korisnickoIme;
        this.lozinka = lozinka;
        this.email = email;
        this.nazivBiografije = nazivBiografije;
        this.stanje = stanje;
    }

    public Korisnik(String ime, String prezime, String korisnickoIme, String lozinka, String nacionalnost, String zemljaZaposlenja, String nioZaposlenja, String naucnoZvanje, String angazovanje, String strucneOblasti, String mobilni, String email, String adresa, String vebStranica, String nazivBiografije, Long privremenaLozinkaPostavljena, String stanje, Set korisnikProjekats) {
        this.ime = ime;
        this.prezime = prezime;
        this.korisnickoIme = korisnickoIme;
        this.lozinka = lozinka;
        this.nacionalnost = nacionalnost;
        this.zemljaZaposlenja = zemljaZaposlenja;
        this.nioZaposlenja = nioZaposlenja;
        this.naucnoZvanje = naucnoZvanje;
        this.angazovanje = angazovanje;
        this.strucneOblasti = strucneOblasti;
        this.mobilni = mobilni;
        this.email = email;
        this.adresa = adresa;
        this.vebStranica = vebStranica;
        this.nazivBiografije = nazivBiografije;
        this.privremenaLozinkaPostavljena = privremenaLozinkaPostavljena;
        this.stanje = stanje;
        this.korisnikProjekats = korisnikProjekats;
    }

    public int brojNeocenjenihProjekata() { // ja dodala
        Iterator<KorisnikProjekat> projekti = korisnikProjekats.iterator();
        int brojac = 0;
        while (projekti.hasNext()) {
            if (!projekti.next().getStanjeOdgovora().equals("poslati")) {
                brojac++;
            }
        }
        return brojac;
    }

    public Integer getIdkorisnik() {
        return this.idkorisnik;
    }

    public void setIdkorisnik(Integer idkorisnik) {
        this.idkorisnik = idkorisnik;
    }

    public String getIme() {
        return this.ime;
    }

    public void setIme(String ime) {
        this.ime = ime;
    }

    public String getPrezime() {
        return this.prezime;
    }

    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }

    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }

    public String getLozinka() {
        return this.lozinka;
    }

    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }

    public String getNacionalnost() {
        return this.nacionalnost;
    }

    public void setNacionalnost(String nacionalnost) {
        this.nacionalnost = nacionalnost;
    }

    public String getZemljaZaposlenja() {
        return this.zemljaZaposlenja;
    }

    public void setZemljaZaposlenja(String zemljaZaposlenja) {
        this.zemljaZaposlenja = zemljaZaposlenja;
    }

    public String getNioZaposlenja() {
        return this.nioZaposlenja;
    }

    public void setNioZaposlenja(String nioZaposlenja) {
        this.nioZaposlenja = nioZaposlenja;
    }

    public String getNaucnoZvanje() {
        return this.naucnoZvanje;
    }

    public void setNaucnoZvanje(String naucnoZvanje) {
        this.naucnoZvanje = naucnoZvanje;
    }

    public String getAngazovanje() {
        return this.angazovanje;
    }

    public void setAngazovanje(String angazovanje) {
        this.angazovanje = angazovanje;
    }

    public String getStrucneOblasti() {
        return this.strucneOblasti;
    }

    public void setStrucneOblasti(String strucneOblasti) {
        this.strucneOblasti = strucneOblasti;
    }

    public String getMobilni() {
        return this.mobilni;
    }

    public void setMobilni(String mobilni) {
        this.mobilni = mobilni;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAdresa() {
        return this.adresa;
    }

    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }

    public String getVebStranica() {
        return this.vebStranica;
    }

    public void setVebStranica(String vebStranica) {
        this.vebStranica = vebStranica;
    }

    public String getNazivBiografije() {
        return this.nazivBiografije;
    }

    public void setNazivBiografije(String nazivBiografije) {
        this.nazivBiografije = nazivBiografije;
    }

    public Long getPrivremenaLozinkaPostavljena() {
        return this.privremenaLozinkaPostavljena;
    }

    public void setPrivremenaLozinkaPostavljena(Long privremenaLozinkaPostavljena) {
        this.privremenaLozinkaPostavljena = privremenaLozinkaPostavljena;
    }

    public String getStanje() {
        return this.stanje;
    }

    public void setStanje(String stanje) {
        this.stanje = stanje;
    }

    public Set getKorisnikProjekats() {
        return this.korisnikProjekats;
    }

    public void setKorisnikProjekats(Set korisnikProjekats) {
        this.korisnikProjekats = korisnikProjekats;
    }

}
