package model;
// Generated Dec 6, 2019 10:16:38 PM by Hibernate Tools 4.3.1



/**
 * KorisnikOdgovor generated by hbm2java
 */
public class KorisnikOdgovor  implements java.io.Serializable {


     private KorisnikOdgovorId id;
     private KorisnikProjekat korisnikProjekat;
     private Odgovor odgovor;
     private Pitanje pitanje;

    public KorisnikOdgovor() {
    }

    public KorisnikOdgovor(KorisnikOdgovorId id, KorisnikProjekat korisnikProjekat, Odgovor odgovor, Pitanje pitanje) {
       this.id = id;
       this.korisnikProjekat = korisnikProjekat;
       this.odgovor = odgovor;
       this.pitanje = pitanje;
    }
   
    public KorisnikOdgovorId getId() {
        return this.id;
    }
    
    public void setId(KorisnikOdgovorId id) {
        this.id = id;
    }
    public KorisnikProjekat getKorisnikProjekat() {
        return this.korisnikProjekat;
    }
    
    public void setKorisnikProjekat(KorisnikProjekat korisnikProjekat) {
        this.korisnikProjekat = korisnikProjekat;
    }
    public Odgovor getOdgovor() {
        return this.odgovor;
    }
    
    public void setOdgovor(Odgovor odgovor) {
        this.odgovor = odgovor;
    }
    public Pitanje getPitanje() {
        return this.pitanje;
    }
    
    public void setPitanje(Pitanje pitanje) {
        this.pitanje = pitanje;
    }




}


