package model;
// Generated Dec 6, 2019 10:16:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Obavestenje generated by hbm2java
 */
public class Obavestenje  implements java.io.Serializable {


     private Integer idobavestenje;
     private String naslov;
     private String tekst;
     private String potpis;
     private Date datum;

    public Obavestenje() {
    }

    public Obavestenje(String naslov, String tekst, String potpis, Date datum) {
       this.naslov = naslov;
       this.tekst = tekst;
       this.potpis = potpis;
       this.datum = datum;
    }
   
    public Integer getIdobavestenje() {
        return this.idobavestenje;
    }
    
    public void setIdobavestenje(Integer idobavestenje) {
        this.idobavestenje = idobavestenje;
    }
    public String getNaslov() {
        return this.naslov;
    }
    
    public void setNaslov(String naslov) {
        this.naslov = naslov;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }
    public String getPotpis() {
        return this.potpis;
    }
    
    public void setPotpis(String potpis) {
        this.potpis = potpis;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


