package model;
// Generated Dec 6, 2019 10:16:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Pitanje generated by hbm2java
 */
public class Pitanje implements java.io.Serializable {

    private Integer idpitanje;
    private ProgramskiPoziv programskiPoziv;
    private String tekst;
    private Set odgovors = new HashSet(0);
    private Set korisnikOdgovors = new HashSet(0);

    // dodato naknadno za prikaz
    private String[] tekstoviOdgovora;

    public Pitanje() {
    }

    public Pitanje(ProgramskiPoziv programskiPoziv, String tekst) {
        this.programskiPoziv = programskiPoziv;
        this.tekst = tekst;
    }

    public Pitanje(ProgramskiPoziv programskiPoziv, String tekst, Set odgovors, Set korisnikOdgovors) {
        this.programskiPoziv = programskiPoziv;
        this.tekst = tekst;
        this.odgovors = odgovors;
        this.korisnikOdgovors = korisnikOdgovors;
    }

    public Integer getIdpitanje() {
        return this.idpitanje;
    }

    public void setIdpitanje(Integer idpitanje) {
        this.idpitanje = idpitanje;
    }

    public ProgramskiPoziv getProgramskiPoziv() {
        return this.programskiPoziv;
    }

    public void setProgramskiPoziv(ProgramskiPoziv programskiPoziv) {
        this.programskiPoziv = programskiPoziv;
    }

    public String getTekst() {
        return this.tekst;
    }

    public void setTekst(String tekst) {
        this.tekst = tekst;
    }

    public Set getOdgovors() {
        return this.odgovors;
    }

    public void setOdgovors(Set odgovors) {
        this.odgovors = odgovors;
    }

    public Set getKorisnikOdgovors() {
        return this.korisnikOdgovors;
    }

    public void setKorisnikOdgovors(Set korisnikOdgovors) {
        this.korisnikOdgovors = korisnikOdgovors;
    }

    public String[] getTekstoviOdgovora() {
        return tekstoviOdgovora;
    }

    public void setTekstoviOdgovora(String[] tekstoviOdgovora) {
        this.tekstoviOdgovora = tekstoviOdgovora;
    }

}
