package model;
// Generated Dec 6, 2019 10:16:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProgramskiPoziv generated by hbm2java
 */
public class ProgramskiPoziv  implements java.io.Serializable {


     private Integer idprogramskiPoziv;
     private String naziv;
     private Set pitanjes = new HashSet(0);
     private Set projekats = new HashSet(0);

    public ProgramskiPoziv() {
    }

	
    public ProgramskiPoziv(String naziv) {
        this.naziv = naziv;
    }
    public ProgramskiPoziv(String naziv, Set pitanjes, Set projekats) {
       this.naziv = naziv;
       this.pitanjes = pitanjes;
       this.projekats = projekats;
    }
   
    public Integer getIdprogramskiPoziv() {
        return this.idprogramskiPoziv;
    }
    
    public void setIdprogramskiPoziv(Integer idprogramskiPoziv) {
        this.idprogramskiPoziv = idprogramskiPoziv;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set getPitanjes() {
        return this.pitanjes;
    }
    
    public void setPitanjes(Set pitanjes) {
        this.pitanjes = pitanjes;
    }
    public Set getProjekats() {
        return this.projekats;
    }
    
    public void setProjekats(Set projekats) {
        this.projekats = projekats;
    }




}


